version: '3.8'

services:
  backend:
    container_name: flask_service
    build:
      dockerfile: docker/Dockerfile_dev
      context: .
    volumes:
      - ./:/srv/flask_app
    ports:
      - "8081:80"
