FROM python:3.11

COPY . /srv/flask_app

WORKDIR /srv/flask_app

RUN apt-get clean \
    && apt-get -y update



RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential \
    && apt-get -y install supervisor

RUN pip install -r req.txt --src /usr/local/src

COPY docker/nginx.conf /etc/nginx
COPY docker/uwsgi.ini /etc/uwsgi/
COPY docker/supervisord.conf /etc/supervisor/conf.d/

ENV APP_ENV="development"

CMD ["/usr/bin/supervisord"]