FROM python:3.6-slim

COPY . /srv/flask_app

WORKDIR /srv/flask_app

RUN apt-get clean \
    && apt-get -y update



RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential

RUN pip install -r req.txt --src /usr/local/src

COPY docker/nginx.conf /etc/nginx

ENV APP_ENV="production"
RUN chmod +x ./start.sh

CMD ["./start.sh"]
